### ISSUE TITLE
Some time mplayer fails

### ISSUE THREAD

**Issue by agherzan** [dbrgn/orochi#44]
Using Fedora 18 with master orochi.

Here is the log:

Skipping track...
Traceback (most recent call last):
  File "/bin/orochi", line 9, in <module>
    load_entry_point('orochi==0.0.1', 'console_scripts', 'orochi')()
  File "/usr/lib/python2.7/site-packages/orochi-0.0.1-py2.7.egg/orochi/client.py", line 733, in main
    client.cmdloop()
  File "/usr/lib/python2.7/site-packages/orochi-0.0.1-py2.7.egg/orochi/client.py", line 168, in cmdloop
    super(Client, self).cmdloop()
  File "/usr/lib64/python2.7/cmd.py", line 142, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib64/python2.7/cmd.py", line 221, in onecmd
    return func(arg)
  File "/usr/lib/python2.7/site-packages/orochi-0.0.1-py2.7.egg/orochi/client.py", line 363, in do_play
    i.cmdloop()
  File "/usr/lib/python2.7/site-packages/orochi-0.0.1-py2.7.egg/orochi/client.py", line 494, in cmdloop
    super(PlayCommand, self).cmdloop()
  File "/usr/lib64/python2.7/cmd.py", line 142, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib64/python2.7/cmd.py", line 221, in onecmd
    return func(arg)
  File "/usr/lib/python2.7/site-packages/orochi-0.0.1-py2.7.egg/orochi/client.py", line 683, in do_n
    self.do_next_song(_args, *_kwargs)
  File "/usr/lib/python2.7/site-packages/orochi-0.0.1-py2.7.egg/orochi/client.py", line 569, in do_next_song
    self.p.load(self.status['track']['url'])
  File "/usr/lib/python2.7/site-packages/orochi-0.0.1-py2.7.egg/orochi/player.py", line 139, in load
    self._send_command('loadfile {}', path)
  File "/usr/lib/python2.7/site-packages/orochi-0.0.1-py2.7.egg/orochi/player.py", line 113, in _send_command
    self.p.write(command.format(*safe_args) + '\n')
  File "/usr/lib/python2.7/site-packages/orochi-0.0.1-py2.7.egg/orochi/player.py", line 27, in __getattr__
    raise TerminatedError('MPlayer has been terminated and cannot be used anymore.')
orochi.errors.TerminatedError: MPlayer has been terminated and cannot be used anymore.

**Comment by agherzan** [comment]
It looks like an old issue - most probably outdated. Closing for now.
