### ISSUE TITLE
AttributeError: 'Client' object has no attribute '_results_per_page'

### ISSUE THREAD

**Issue by vmalloc** [dbrgn/orochi#61]
```
Traceback (most recent call last):
  File "/Users/rotemy/.virtualenv/bin/orochi", line 11, in <module>
    sys.exit(main())
  File "/Users/rotemy/.virtualenv/lib/python2.7/site-packages/orochi/client.py", line 732, in main
    client.cmdloop()
  File "/Users/rotemy/.virtualenv/lib/python2.7/site-packages/orochi/client.py", line 169, in cmdloop
    super(Client, self).cmdloop()
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/cmd.py", line 142, in cmdloop
    stop = self.onecmd(line)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/cmd.py", line 221, in onecmd
    return func(arg)
  File "/Users/rotemy/.virtualenv/lib/python2.7/site-packages/orochi/client.py", line 406, in do_liked_mixes
    self.do_search_user_liked(self._user_name)
  File "/Users/rotemy/.virtualenv/lib/python2.7/site-packages/orochi/client.py", line 250, in do_search_user_liked
    mixes = self.search_request(s, 'user_liked')
  File "/Users/rotemy/.virtualenv/lib/python2.7/site-packages/orochi/client.py", line 423, in search_request
    self.config['results_sorting'], self._search_results_page, self._results_per_page)
AttributeError: 'Client' object has no attribute '_results_per_page'
```

**Comment by dbrgn** [comment]
Thanks for the report. What action did you take that caused the crash? Could you reproduce it?

**Comment by vmalloc** [comment]
It doesn't reproduce - but it happened when I logged in and then ran `liked_mixes`
